name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.9", "3.10"]
        req-version: ["oldest", "middle", "newest"]
        os: ["ubuntu-22.04"]
        exclude:
          - python-version: "3.7"
            req-version: "newest"
          - python-version: "3.9"
            req-version: "oldest"
          - python-version: "3.10"
            req-version: "oldest"
          - python-version: "3.10"
            req-version: "middle"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements ${{ matrix.req-version }}
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements-${{ matrix.req-version }}.txt
        pip install pytest pytest-cov
        pip install .
    - name: Run tests
      run: |
        pytest --cov=lazyarray -v
  #   - name: Upload coverage data
  #     run: |
  #       coveralls --service=github
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
  #       COVERALLS_PARALLEL: true
  # coveralls:
  #   name: Indicate completion to coveralls.io
  #   needs: test
  #   runs-on: ubuntu-latest
  #   container: python:3-slim
  #   steps:
  #   - name: Finished
  #     run: |
  #       pip3 install --upgrade coveralls
  #       coveralls --service=github --finish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}